package game.controller;

public enum ClientState {                   //Used from GUI
    CHOOSEWEAPONTOWASTE,
    CHOOSEWEAPONTOGRAB,
    CHOOSESTEP,
    CHOOSEACTIOIN,
    CHOOSEWEAPONTOSHOOT,
    CHOOSEPBB,
    CHOOSEFIRSTEFFECT,
    CHOOSEPLUSORDER,
    CHOOSEPLUSEFFECT,
    CHOOSERELOAD,
    CHOOSECOUNTER,
    CHOOSECARDPOWER,
    CHOOSESCOPE,
    WAITING_GRAB_WEAPON,                    //Used from Client Context
    WAITING_GRAB_AMMO,
    WAITING_SHOOT,
    WAITING_ACTION,
    GAME_END,
    WAITING_SPAWN,
    WAITING_START,
    TIMED_OUT,
    HANDLING_MOVEMENT;
}
